server:
  port: 1998

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shms_db?useSSL=false&serverTimezone=UTC
    username: nakdev
    password: Linux@1998
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    org.nakhan: DEBUG
    org.springframework.security: DEBUG
